name: Typo Check

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]
        paths:
            - '**/*.md'
            - '**/*.txt'
            - 'src/**/*.ts'
            - 'src/**/*.tsx'
            - 'src/**/*.js'
            - 'src/**/*.jsx'

jobs:
    typo-check:
        name: Check for typos
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Install cspell
              run: npm install -g cspell

            - name: Check for spelling errors
              run: |
                cspell "**/*.md" "**/*.txt" "src/**/*.{ts,tsx,js,jsx}" --config .cspell.json